### ISSUE TITLE
Search doesn't work as expected

### ISSUE THREAD

**Issue by nextchamp-saqib** [frappe/gameplan#21] opened 2022-08-11 06:15 UTC
Search doesn't work as expected 

<img width="692" alt="CleanShot 2022-08-11 at 10 45 19@2x" src="https://user-images.githubusercontent.com/25369014/184074408-bea479f4-26d6-493c-b644-609bb4a82b00.png">

**Comment by netchampfaris** [comment] 2022-10-06 20:45
Duplicate of #116

**Closed by netchampfaris** 2022-10-06 20:45 UTC
