### ISSUE TITLE
feat: Results page for Forum search

### ISSUE THREAD

**Issue by ruthra-kumar** [frappe/gameplan#43] opened 2022-08-16 08:06 UTC
## 1 - Search Result Page
Currently, Search results are only shown in drop down list. Result page, similar to how discourse does should be included.

While browsing for content in the forum, its taxing to re-enter the search term every time I want to visit a different thread from the search result.

## 2 - Drop down with hyperlinks
Search results should be hyperlinks, including the drop down list. With this, multiple browser tabs can be opened from search result. This is a major quality of life improvement.

**Comment by netchampfaris** [comment] 2022-10-06 20:45
Duplicate of #116

**Closed by netchampfaris** 2022-10-06 20:45 UTC
