### ISSUE TITLE
Email Notification for mentions

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/gameplan#91] opened 2022-09-13 08:51 UTC
.

**Comment by NagariaHussain** [comment] 2022-09-26 07:36
> Opinionated view: gameplan is async communication tool for teams, so it shouldn't have annoying notifications that get clubbed with the rest of the emails.
> 
> 
> 
> This can be provided as an option though, hopefully disabled by default. 
> 
> 
> 
> 
> 
> 

We can do something similar to what [twist](https://twist.com) does. So, not a immediate notification, but some kind of reminder of pending unread notifications.

**Comment by netchampfaris** [comment] 2022-10-06 20:33
Duplicate of https://github.com/frappe/gameplan/issues/115

**Closed by netchampfaris** 2022-10-06 20:33 UTC
Labels: enhancement
